version: '3.9'

services:
  backend:
    build: ./backend
    ports:
      - "7860:7860"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
